spring.application.name=FarmConnect
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/farmconnectdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
# Key must be at least 256 bits (32 characters)
farmconnect.app.jwtSecret=FarmConnectSecretKey89234789234789234897238947
farmconnect.app.jwtExpirationMs=86400000
